<?php

/*
	* Admin Custom Pages Module v 1.0.4
	* Create custom admin pages without building a Process Module
	*
	* @author Diogo Oliveira
	*
	* ProcessWire 2.x
	* Copyright (C) 2011 by Ryan Cramer
	* Licensed under GNU/GPL v2, see LICENSE.TXT
	*
	* http://www.processwire.com
	*
*/

class ProcessAdminCustomPages extends Process {
	
	static public function getModuleInfo() {
		return array(
			'title'   => 'Admin Custom Pages',
			'summary' => 'Create custom admin pages without building a Process Module',
			'version' => 105,
			'author'  => 'Diogo Oliveira',
			'permission' => 'page-view'
		);
	}

	public function init() {

		parent::init();

		// load script and style files for this page (expects a ACP_scripts_and_styles field with one url per line)
		if ($this->page->ACP_scripts_and_styles != "") {

			// get one url for each line of the field
			$files = explode("\n", $this->page->ACP_scripts_and_styles);

			foreach ($files as $f) {

				// get the file extension
				$extension = trim(substr(strrchr($f,'.'),1));
				
				// check if url is absolute, if not concatenate it with the site root url
				if (strpos($f, "http://") === false) {
					$f = $this->config->urls->root . $f;
				}

				// load the correct type of file
				switch ($extension) {

					case "js":
						$this->config->scripts->add($f);
						break;

					case "css":
						$this->config->styles->add($f);
						break;
				}
			}
		}
	}

	public function ___execute() {

		$template_file = $this->config->paths->templates . $this->page->template->name . ".php";

		if (file_exists($template_file)) {

			// only works with dev version of ProcessWire May 8 2013
			return $this->page->render($template_file);

		} elseif ($this->page->child->id) {

			// for the current stable version use this method
			// 'include=hidden' added by suggestion of Macrura and kongondo at the forum
			// http://processwire.com/talk/topic/3474-admin-custom-pages-module/?p=38304
			return $this->page->child('include=hidden')->render();

		} else {

			return $this->error("You should provide either a file named {$this->page->template->name}.php in your templates folder (for DEV version of PW), or a child of this page to render here"); 

		}

	}
	
	// install method created by Pete (https://github.com/Notanotherdotcom)
	public function ___install() {
		
		// Copy the admin.php template over the old one
		echo wire('config')->paths->siteModules . 'ProcessAdminCustomPages/admin.php' . '||' . wire('config')->paths->templates . 'admin.php';
		//exit;
		copy ( wire('config')->paths->siteModules . 'ProcessAdminCustomPages/admin.php', wire('config')->paths->templates . 'admin.php');
		
		// Check for existence of the field below, throw a message if it already exists
		if($this->fields->get('ACP_scripts_and_styles')) {
			//$this->error("You already have a 'ACP_scripts_and_styles' field.");
			return;
		}

		// If it doesn't exist then carry on and create it
		$field = new Field();
		$field->type = $this->modules->get("FieldtypeTextarea");
		$field->name = 'ACP_scripts_and_styles';
		$field->label = 'Scripts and styles for admin pages';
		$field->description = 'Add the .js and .css URLs in this field textarea, one in each line. can be absolute or relative (relative is assumed from the site root eg: site/templates/styles/my.css)';
		$field->save();

		$this->message("Added field 'ACP_scripts_and_styles'. Add this field to the page template of your custom admin pages when needed.");
		
	}
    
} 
