<?php

/*
	* Admin Custom Pages Module v 1.0.1
	* Create custom admin pages without building a Process Module
	*
	* @author Diogo Oliveira
	*
	* ProcessWire 2.x
	* Copyright (C) 2011 by Ryan Cramer
	* Licensed under GNU/GPL v2, see LICENSE.TXT
	*
	* http://www.processwire.com
	*
*/

class ProcessAdminCustomPages extends Process {
	
	static public function getModuleInfo() {
		return array(
			'title'   => 'Admin Custom Pages',
			'summary' => 'Create custom admin pages without building a Process Module',
			'version' => 101,
			'author'  => 'Diogo Oliveira'
		);
	}

	public function init() {

		parent::init();

		if ($this->page->ACP_scripts_and_styles != "") {

			$files = explode("\n", $this->page->ACP_scripts_and_styles);

			foreach ($files as $f) {

				$extension = trim(substr(strrchr($f,'.'),1));
				
				if (strpos($f, "http://") === false) {
					$f = $this->config->urls->root . $f;
				}

				switch ($extension) {

					case "js":
						wire('config')->scripts->add($f);
						break;

					case "css":
						wire('config')->styles->add($f);
						break;
				}
			}
		}
	}

	public function ___execute() {

		if ($this->page->ACP_render_file != "") {

			return $this->page->render($this->page->ACP_render_file);

		} elseif ($this->page->child->id) {

			return $this->page->child->render();

		} else {

			return $this->error("You didn't provide a file name (ACP_render_file field) or a child of this page to render");

		}

	}
    
}
